name: Continuous Integration

on: [push, pull_request]


jobs:
  build:
    name: FluidSynth + sndfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./build.sh

    - name: Create Package
      run: |
        mkdir package
        cp build/i686/bin/*.dll build/x86_64/bin/*.dll package

    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        path: package
        name: fluidsynth_sndfile

    # - name: List Directory
    #   if: always()
    #   shell: bash
    #   run: |
    #     git status
    #     ls -lR .
